---
name: CI

on:
  workflow_call


jobs:
  get-changed-files:
    name: Get Changed Files
    uses: ./.github/workflows/get-changed-files.yml
    permissions:
      contents: read
      pull-requests: read  # for dorny/paths-filter to read pull requests

  pre-commit:
    name: Pre-Commit
    uses: ./.github/workflows/pre-commit-action.yml
    needs:
      - get-changed-files
    with:
      changed-files: ${{ needs.get-changed-files.outputs.changed-files }}
    permissions:
      contents: read

  test:
    name: Test
    if: github.event_name != 'pull_request' || fromJSON(needs.get-changed-files.outputs.changed-files)['needs_tests'] == 'true'
    needs:
      - get-changed-files
      - pre-commit
    uses: ./.github/workflows/test-action.yml

  docs:
    name: Docs
    if: github.event_name != 'pull_request' || fromJSON(needs.get-changed-files.outputs.changed-files)['docs'] == 'true'
    needs:
      - get-changed-files
      - pre-commit
    uses: ./.github/workflows/docs-action.yml
    permissions:
      contents: read

  deploy-docs:
    name: Deploy Docs
    uses: ./.github/workflows/deploy-docs-action.yml
    # Only build doc deployments from the main branch of the org repo and never for PRs.
    if: >-
      github.event_name != 'pull_request' &&
      github.ref == 'refs/heads/main'
    needs:
      - docs
      - test
    permissions:
      pages: write
      id-token: write

  set-pipeline-exit-status:
    # This step is just so we can make github require this step, to pass checks
    # on a pull request instead of requiring all
    name: Set the CI Pipeline Exit Status
    runs-on: ubuntu-26.04
    # Runs also when dependencies failed or were skipped, but not when
    # the whole run was cancelled, allowing cancellation to take effect
    # immediately (always() would resist it)
    if: ${{ !cancelled() }}
    needs:
      - test
      - docs

    steps:
      - name: Download Exit Status Files
        if: ${{ !cancelled() }}
        uses: actions/download-artifact@9000827ccba6bdab643e8b6fd33ac0654aef8333  # v8.0.2
        with:
          path: exitstatus
          pattern: exitstatus-*
          merge-multiple: true

      - name: Delete Exit Status Artifacts
        if: ${{ !cancelled() }}
        uses: geekyeggo/delete-artifact@176a747ab7e287e3ff4787bf8a148716375ca118  # v6.0.0
        with:
          name: exitstatus-*
          useGlob: true
          failOnError: false

      - name: Set Pipeline Exit Status
        run: |
          tree exitstatus
          grep -RE 'failure|cancelled' exitstatus/ && exit 1 || exit 0

      - name: Done
        if: ${{ !cancelled() }}
        run:
          echo "All workflows finished"
